### ISSUE TITLE
Not blocking shortkeys with Windows modifier

### ISSUE THREAD

**Issue by TuTAH1** [kfirprods/NonInvasiveKeyboardHook#11]
The issue is just the header. When I assign an action to Win+1 shortcut, keyboardHookManager reacting on this and perform an action needed, BUT the default windows action is performed too.

**Comment by TuTAH1** [comment]
For now I use a workaround: In the registry, in [HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced].DisabledHotKeys (expandable string parameter) I wrote the keys (1 char in this string = 1 key) I need to disable from Windows' control (in my case, it's "123")

**Comment by TuTAH1** [comment]
As it turned out, this is not the solution – win+# don't making an action now, but the shortcut still passes, as result, printing # (# = number)

**Comment by kfirprods** [comment]
It's been a long time since I've used the library myself, so I'm a bit rusty, but if I'm not mistaken the library is written in a way that lets all the keys through, regardless of whether or not they are registered as hotkeys.

Personally, I never used the library in a context that involves user input, and I don't think that I ever used the winkey modifier either.

Sorry I couldn't be more helpful here. If you'd like, you can try to create a Pull Request that allows registering hotkeys that "block" the shortcut, just make sure not to break the current default behavior
